name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/
    - name: Build
      run: dotnet build ./src/ --no-restore   
    - name: Test
      run: dotnet test ./src/ --no-build --verbosity normal   

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: nuget
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x    
    - name: Build
      run: dotnet pack --configuration Release ./src/ -o ./
    - name: Publish
      env: 
        API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push --api-key $API_KEY --source https://api.nuget.org/v3/index.json *.nupkg
      
